-- =========================================================
-- STUDENT MANAGEMENT - SUPABASE SETUP
-- Run this in Supabase SQL Editor if you need to recreate it.
-- =========================================================

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text,
    course text,
    marks bigint
);

alter table public.students enable row level security;

-- Development / learning policies.
-- These are intentionally permissive for this CRUD demo.

drop policy if exists "Allow public select" on public.students;
drop policy if exists "Allow public insert" on public.students;
drop policy if exists "Allow public update" on public.students;
drop policy if exists "Allow public delete" on public.students;

create policy "Allow public select"
on public.students
as permissive
for select
to public
using (true);

create policy "Allow public insert"
on public.students
as permissive
for insert
to public
with check (true);

create policy "Allow public update"
on public.students
as permissive
for update
to public
using (true)
with check (true);

create policy "Allow public delete"
on public.students
as permissive
for delete
to public
using (true);
